Prepare function in R which translate offline (without access to network) Ensembl Ids to Hugo gene names.  
Function should accept one variable with ids (one or thousands of ids), detect type of  ids and translate it into other type of ids. 
Example: 
ENSG00000133703 -> KRAS
ENST00000256078.10 -> KRAS
KRAS -> ENSG00000133703

File with ids to translate is attached (test_ids_input.tsv).

```{r}
library(stringr)
library(maps)

remove_suffix <- function(ensembl_id) {
  return(str_remove(ensembl_id, "\\.\\d+"))
}

detect_id_type <- function(name) {
  sub = substr(name, 1, 4)
  if(sub == "ENSG") {
    return("ens_gene")
  }
  else if(sub == "ENST") {
    return("ens_transcript")
  }
  return("hugo_gene")
}

transcript_to_gene <- function(transcript, ensembl_table) {
  gene_id = ensembl_table[1]
  transcript_id = ensembl_table[2]
  return(gene_id[transcript_id == transcript])
}

read_tables <- function(ensembl_path, hugo_path) {
  ensembl_table <<- read.table(file=ensembl_path)
  hugo_table <<- read.table(file=hugo_path, , sep="\t", fill = TRUE)
  hugo_gene <<- hugo_table[2]
  hugo_ens <<- hugo_table[3]
  gene_id <<- ensembl_table[1]
  transcript_id <<- ensembl_table[2]
}

```


```{r}

ensembl_table = "test_ids_input.tsv"
hugo_table = "hgnc_custom.tsv"
#ensembl_table ="test/ensembl_ids_test.tsv"
#hugo_table = "test/hugo_test.tsv"

translate <- function(query, ensembl_table, hugo_table) {
  read_tables(ensembl_table, hugo_table)
  type = detect_id_type(query)
  if(type == "ens_gene") {
    print(hugo_gene[hugo_ens == remove_suffix(query)])
    return(hugo_gene[hugo_ens == remove_suffix(query)])
  }
  else if(type == "ens_transcript") {
    gene = remove_suffix(transcript_to_gene(query, ensembl_table))
    return(hugo_gene[hugo_ens == gene])
  }
  id = hugo_ens[hugo_gene == query]
  return(gene_id[remove_suffix(gene_id) == id])
}

translate("ENSG00000151360", ensembl_table, hugo_table)

```
TESTS
```{r}
read_tables("test/ensembl_ids_test.tsv", "test/hugo_test.tsv")
detect_id_type("ENSG00000151360") == "ens_gene"
detect_id_type("ENST00000151360") == "ens_transcript"
detect_id_type("KRAS") == "hugo_gene"

transcript_to_gene("ENST00000496771.1", ensembl_table) == "ENSG00000000003.10"

remove_suffix("ENST00000373031.4")
translate("ENSG00000151360", ensembl_table, hugo_table)# == "allantoicase"
translate("ENST00000373031.4", ensembl_table, hugo_table) == "tenomodulin"
translate("KRAS", ensembl_table, hugo_table)
```

